name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: 'package.json'
          node-version: "18"
          cache: "pnpm"
      - name: Pnpm install
        run: pnpm install
      - name: Lint
        run: pnpm lint

  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: 'package.json'
          node-version: "18"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Basic Development Tests
        run: pnpm test:development
