name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - beta
      - release
      - 'release-*'
      - 'lts-*'
    tags:
      - '*'

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Yarn install
        run: yarn --frozen-lockfile
      - name: Lint js
        run: yarn lint:js

  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Basic Development Tests
        run: yarn test:development
